# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    'master':
      - step:
          name: Deploy Application
          image: nikolaik/python-nodejs:python3.7-nodejs14
          deployment: PROD  
          caches:
            - pip
            - docker
            - node
          script:
            - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - cd backend
            - npm install -g serverless
            - npm install
            - serverless deploy -v