service: projeto-pdf-backend

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
        - "lambda:InvokeFunction"
      Resource: "*"

functions:
  mesclador:
    handler: functions/mesclador.handler
    events:
      - http:
          method: post
          path: api/mesclador
          cors: true

  processador:
    handler: functions/processador.handler
    runtime: nodejs14.x
    events:
      - http:
          method: post
          path: api/processador
          cors: true        

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-apigw-binary

custom:
  pythonRequirements:
    dockerizePip: non-linux
  apigwBinary:
    types:
      - '*/*'

